name: pilem
description: "A new Flutter project."

# Mencegah package dipublikasikan secara tidak sengaja ke pub.dev
publish_to: 'none'

# Versi aplikasi
version: 1.0.0+1

# Versi environment SDK Dart yang digunakan
environment:
  sdk: ">=3.5.3 <4.0.0"

# Dependencies aplikasi
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  cupertino_icons: ^1.0.8
  http: ^1.3.0

# Dependencies untuk pengujian dan linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Konfigurasi Flutter
flutter:
  uses-material-design: true
