// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0R63KN2p8K7pUbnp_89sUs9PR5pQhcpk',
    appId: '1:203940600113:web:172791216bd3316c787810',
    messagingSenderId: '203940600113',
    projectId: 'first-app-8c352',
    authDomain: 'first-app-8c352.firebaseapp.com',
    databaseURL: 'https://first-app-8c352-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-8c352.firebasestorage.app',
    measurementId: 'G-7VWKHH4BJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvWFsMmT_-h69CpdCkSG6hrsCweIdwg_Q',
    appId: '1:203940600113:android:997aa44c99368b5b787810',
    messagingSenderId: '203940600113',
    projectId: 'first-app-8c352',
    databaseURL: 'https://first-app-8c352-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-8c352.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0R63KN2p8K7pUbnp_89sUs9PR5pQhcpk',
    appId: '1:203940600113:web:172791216bd3316c787810',
    messagingSenderId: '203940600113',
    projectId: 'first-app-8c352',
    authDomain: 'first-app-8c352.firebaseapp.com',
    databaseURL: 'https://first-app-8c352-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-8c352.firebasestorage.app',
    measurementId: 'G-7VWKHH4BJK',
  );

}