// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeLImfVTBz2k3sDMGM9ufcFO3HbYD4JBU',
    appId: '1:535726058169:web:bd1bd01101800c854cc968',
    messagingSenderId: '535726058169',
    projectId: 'fasum-d8b29',
    authDomain: 'fasum-d8b29.firebaseapp.com',
    databaseURL: 'https://fasum-d8b29-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-d8b29.firebasestorage.app',
    measurementId: 'G-KJJNM72691',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA5VNyR9O85V13e8l4H8zl83lPtU1O9cg',
    appId: '1:535726058169:android:7936f9dbe91616d14cc968',
    messagingSenderId: '535726058169',
    projectId: 'fasum-d8b29',
    databaseURL: 'https://fasum-d8b29-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-d8b29.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeLImfVTBz2k3sDMGM9ufcFO3HbYD4JBU',
    appId: '1:535726058169:web:973a7f7b66a55da14cc968',
    messagingSenderId: '535726058169',
    projectId: 'fasum-d8b29',
    authDomain: 'fasum-d8b29.firebaseapp.com',
    databaseURL: 'https://fasum-d8b29-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-d8b29.firebasestorage.app',
    measurementId: 'G-HP25CNNW8C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRYmDHbjTqJ9JE64_1KiiHvvahfNc5cQA',
    appId: '1:535726058169:ios:17803a882922dac04cc968',
    messagingSenderId: '535726058169',
    projectId: 'fasum-d8b29',
    databaseURL: 'https://fasum-d8b29-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-d8b29.firebasestorage.app',
    iosClientId: '535726058169-48sdp853ln6qjdpah5lmgojpurgmrhhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRYmDHbjTqJ9JE64_1KiiHvvahfNc5cQA',
    appId: '1:535726058169:ios:17803a882922dac04cc968',
    messagingSenderId: '535726058169',
    projectId: 'fasum-d8b29',
    databaseURL: 'https://fasum-d8b29-default-rtdb.firebaseio.com',
    storageBucket: 'fasum-d8b29.firebasestorage.app',
    iosClientId: '535726058169-48sdp853ln6qjdpah5lmgojpurgmrhhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

}

// link api gemini Hendri : AIzaSyB1iZHGceX8xLdBcVzF5uiBE2NMLXj1rrM