// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG3R8ENlwia-LMSXGZjgp5U57-j-pFD4g',
    appId: '1:523814141377:web:ea4b48c9e5de7890f08340',
    messagingSenderId: '523814141377',
    projectId: 'first-app-97429',
    authDomain: 'first-app-97429.firebaseapp.com',
    databaseURL: 'https://first-app-97429-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-97429.firebasestorage.app',
    measurementId: 'G-5JSSHT397V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCupKZsKmf_EK5PdAQ5UiSyTBXU4ttKhxU',
    appId: '1:523814141377:android:bb5bb0b6d98fb25ef08340',
    messagingSenderId: '523814141377',
    projectId: 'first-app-97429',
    databaseURL: 'https://first-app-97429-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-97429.firebasestorage.app',
  );
}
